require("user.options")
require("user.plugins")
require("user.keymaps")

require("user.autopair")
require("user.bufferline")
require("user.cmp")
require("user.comment")
require("user.gitsigns")
require("user.lsp")
require("user.lualine")
require("user.neoclip")
require("user.nvim-tree")
require("user.telescope")
require("user.telescope-emoji")
require("user.toggleterm")
require("user.treesitter")
require("user.vimsneak")
